### ISSUE TITLE
Sandbox / Avalanche crash on map load

### ISSUE THREAD

**Issue by ghost** [TheGuardians/TagTool#1]
When all maps are ported, both sandbox and snowbound crash the game when the maps begin to load. Neither end up finishing the load process before crashing to desktop.

**Comment by Satomilee** [comment]
edittag levels\dlc\sidewinder\shaders\side_tree_branch_snow.rmsh
SetField ShaderProperties[0].Unknown7 0
savetagchanges
exitTo tags


edittag objects\levels\dlc\sandbox\shaders\sandbox_grid_dim.rmhg
editblock shaderproperties[0]
removeblockelements unknown 0 *
addblockelements unknown
savetagchanges
exitTo tags
edittag objects\levels\dlc\sandbox\shaders\sandbox_grid.rmhg
editblock shaderproperties[0]
removeblockelements unknown 0 *
addblockelements unknown
savetagchanges
exitTo tags
