### ISSUE TITLE
All DLC Maps are marked as Guardian

### ISSUE THREAD

**Issue by ghost** [TheGuardians/TagTool#2]
After porting maps in. Any maps that were not shipped with H3 are marked as Guardian in the map list. 

The maps in order from top to bottom are as follows:
1:  Orbital
2:  Either Avalanche or Sandbox (See Issue#1)
3:  Either Avalanche or Sandbox (See Issue#1)
4:  Assembly
5:  Foundry
6:  Citadel
7:  Ghost Town
8:  Guardian
9:  Cold Storage
10: Blackout
11: Heretic
12: Longshore
13: Rats Nest

**Comment by twist84** [comment]
This is due to not having the DLC mapinfos

**Comment by camden-smallwood-zz** [comment]
Yep, make sure when you use `UpdateMapFiles` that you supply the path to `halo3\maps\info\` like this:
```UpdateMapFiles C:\Halo\Maps\H3\info```
