### ISSUE TITLE
Cold Storage can only be played singleplayer

### ISSUE THREAD

**Issue by ghost** [TheGuardians/TagTool#3]
Cold Storage can be loaded and played on. However anyone who tries to join it (even if they have the same installation of the game), will be booted to the menu and the game will end

**Comment by Satomilee** [comment]
edittag objects\levels\solo\060_floodship\flood_danglers\large_dangler\large_dangler.physics_model
removeblockelements PoweredChains 0 *
savetagchanges
exitTo tags

edittag objects\levels\solo\060_floodship\flood_danglers\small_dangler\small_dangler.physics_model
removeblockelements PoweredChains 0 *
savetagchanges
exitTo tags
