### ISSUE TITLE
Citadel turns into Eldorado

### ISSUE THREAD

**Issue by ghost** [TheGuardians/TagTool#4]
The map becomes gold with bloom encompassing the entire map. Pictures attached
<img width="1920" alt="eldorado" src="https://user-images.githubusercontent.com/45273497/48924433-21820e80-ee86-11e8-8eb7-58f92e467cad.png">
<img width="1920" alt="eldorado2" src="https://user-images.githubusercontent.com/45273497/48924434-21820e80-ee86-11e8-8a53-dd6da8323165.png">

**Comment by Satomilee** [comment]
EditTag levels\dlc\fortress\shaders\constantblack.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\dlc\fortress\shaders\panel_pipe_simple.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_panel_wall_inset_decor_blue.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_panel_wall_mech.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\glass_activation.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\glass_control.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_bsp_160_floor.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_ceiling_corner.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_column_activation.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_elevator_generator.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_floor_activation.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_floor_ele.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\dlc\fortress\shaders\panel_platform_center.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_floor_ele_corner.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_glass.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_hall_doorway.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_hall_floor.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_light_ceiling.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_poop_ramp.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_reactor_base.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_wall_alcove.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_wall_control_floor_2.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\100_citadel\shaders\panel_wall_vert.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\dlc\fortress\shaders\panel_wall_alcove.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag objects\levels\multi\salvation\shaders\altar_holo_projector.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\dlc\fortress\shaders\panel_wall_alcove_illum.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\dlc\fortress\shaders\panel_wall_alcove_metal.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\con_panel_wall.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\const_panel_trim_illum.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\deck_floor.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\deck_floor2.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\glass_activation.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\dlc\fortress\shaders\floor_glass.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\glass_floor2.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_080_column.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_080_floor.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_080_wall_back02.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_080_wall_side_silver.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_catwalk.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_cust_arch_int.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_deco_trim.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_door_trim.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_glass.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\dlc\fortress\shaders\forrunnerhologram.shader_halogram
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_glass2.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_hall_floor.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_pipe_simple2.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_plate_ext.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_poop_emitter_core.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_poop_ramp_tech.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_poop_vent.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_waste_poop.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\panel_wedge.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\riverworld_metalplate.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\dlc\fortress\shaders\glass_panel_wall_inset.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\waste_panel_pipe.shader
SetArgument env_tint_color 0 0 0 1
SetArgument normal_specular_tint 0.05 0.05 0.05 0
SetArgument self_illum_intensity 0.005 0.005 0.005 0
savetagchanges 
exit 
EditTag levels\multi\construct\shaders\waste_panel_reactor.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\ext_light_techstrip_warm.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\holo_data_panel.shader_halogram
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\holo_glass_datascroll.shader_halogram
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\light_circle_lift.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\light_circle_lift_unlit.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\light_techbit_cool.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\light_techgradient_cool.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\light_techstrip_warm.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\dlc\fortress\shaders\light_basic_blue.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_cust_arch_int.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_deco_trim.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_deco_trim_ext.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_door_trim.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_door_trim_ext.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_door_trim_illum.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_plate.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_plate_ext.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_simple.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_simple_ext.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\dlc\fortress\shaders\light_basic_red.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_tech_illum_warm.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_tech_railing.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_tech_trim.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_tech_trim_ext.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_wedge.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\panel_wedge_unlit.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\sal_floor_circle.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\sal_floor_hallway.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\sal_floor_tile.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\sal_floor_tile_ext.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\dlc\fortress\shaders\panel_hall_floor.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\sal_glass_floor.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\sal_glass_white.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\sal_glass_white_prepass.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\salvation_terrain.shader_terrain
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\salvation_terrain_ext.shader_terrain
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\trim_trim.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\trim_trim_sm.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\multi\salvation\shaders\z_black.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\panel_080_floor_ceiling.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\dlc\fortress\shaders\panel_pipe_blue.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\panel_080_wall_side.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\panel_catwalk.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\panel_floor_waste.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\panel_generic_simple_int_blue.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\panel_poop_railing.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\panel_waste_poop.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_beam.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_door_frame_small.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_int_light_basic.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_metal_a.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\dlc\fortress\shaders\panel_pipe_red.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_metal_b.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_metal_silver.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_panel_column.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_panel_floor.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_panel_pipe_blue.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_panel_trim.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_panel_trim_blue.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_panel_wall_diagonal.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_panel_wall_horizontal.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit 
EditTag levels\solo\070_waste\shaders\waste_panel_wall_inset.shader
SetArgument env_tint_color 0 0 0 1 
savetagchanges 
exit
EditTag levels\solo\100_citadel\shaders\panel_wall_alcove.shader
setfield ShaderProperties[0].ShaderMaps[0].bitmap levels\dlc\fortress\bitmaps\panel_wall_alcove_diffuse.bitmap
setfield shaderproperties[0].shadermaps[2].bitmap levels\solo\100_citadel\bitmaps\panel_wall_alcove_bump.bitmap
savetagchanges
exit

**Comment by camden-smallwood-zz** [comment]
There's still a couple issues in the skybox, but this fixes it for the most part:
```
foreach "rm  " setargument environment_map_specular_contribution 0 0 0 0

edittag levels\dlc\fortress\shaders\floor_glass.shader
setfield shaderproperties[0].bitmaptransparency 1
savetagchanges
exit```
