### ISSUE TITLE
Visual Oddities on Snowbound

### ISSUE THREAD

**Issue by ghost** [TheGuardians/TagTool#5]
The issues I could find are as follows:
- Shell materials lack color
- Normal maps on gold ramp seem to be messed up
- Snow detail on cliff edges seem to be nonexistant

<img width="1920" alt="snowbound" src="https://user-images.githubusercontent.com/45273497/48924489-e7fdd300-ee86-11e8-93da-4f81d3c4160a.png">
<img width="1920" alt="snowbound2" src="https://user-images.githubusercontent.com/45273497/48924490-e7fdd300-ee86-11e8-8bfa-520dd2ae6190.png">
<img width="1920" alt="snowbound4" src="https://user-images.githubusercontent.com/45273497/48924491-e7fdd300-ee86-11e8-8410-8fcccedc942a.png">
<img width="1440" alt="snowbound3" src="https://user-images.githubusercontent.com/45273497/48924512-21364300-ee87-11e8-9085-b23eb61edcd9.png">

**Comment by Satomilee** [comment]
edittag levels\multi\snowbound\shaders\cov_metalplates_icy.rmsh
editblock shaderproperties[0]
setfield shadermaps[0].bitmap levels\multi\snowbound\bitmaps\metal\fs_panel_f_purple_dif.bitmap
savetagchanges
exitTo tags

edittag levels\multi\snowbound\shaders\cov_glass_window_opaque.rmsh
setfield ShaderProperties[0].Template shaders\shader_templates\_0_2_0_1_7_0_0_0_0_1_0.rmt2
editblock shaderproperties[0]
setargument bump_detail_coefficient 5 5 5 5
setargument specular_coefficient 0.2 0.2 0.2 0.2
setargument analytical_specular_contribution 100 100 100 100
setargument roughness 0.2 0.2 0.2 0.2
setargument area_specular_contribution 0.1 0.1 0.1 0.1
setargument specular_tint 0.5 0.3 0.1 1
savetagchanges
exitto tags
