### ISSUE TITLE
Feature Request: Additional Tag Support

### ISSUE THREAD

**Issue by ghost** [TheGuardians/TagTool#53]
### (Reach: Retail) Feature Request: Tag Support

**Tags: wxcg, rain, ssao, wpdp, cpem, atgf**

_I've Doing some large scale Reach Tag Testing, and these tags would be nice to have.
Is it possible to have support added for these Tags at some point?_

**Comment by yokimklein** [comment]
These tag groups didn’t exist in blam before Reach so they can’t be ported to older engine versions.

**Comment by ghost** [comment]
The Engine in Question (ms23 - ms30) already utilizes Reach Tags. When Ported to a Main-Menu Cache, The Tags will function fine.

**Comment by twist84** [comment]
The tag groups in question have no support in the Halo Online version of the engine.
