### ISSUE TITLE
Visual Oddities on Orbital

### ISSUE THREAD

**Issue by ghost** [TheGuardians/TagTool#6]
The issues I could find are as follows:
- Ground Cubemap causes some odd discoloration
- Smoke Particles on generator show up as white squares
- Door Normals are messed up
- Cubemap on Glass obscures whats behind it at certain angles

<img width="1440" alt="orbital" src="https://user-images.githubusercontent.com/45273497/48924751-81c67f80-ee89-11e8-9fdf-f31bb9805919.png">
<img width="1440" alt="orbital2" src="https://user-images.githubusercontent.com/45273497/48924752-81c67f80-ee89-11e8-95b4-814188cac36f.png">
<img width="1440" alt="orbital3" src="https://user-images.githubusercontent.com/45273497/48924748-81c67f80-ee89-11e8-953c-0bfe1aba21d6.png">
<img width="1440" alt="orbital4" src="https://user-images.githubusercontent.com/45273497/48924749-81c67f80-ee89-11e8-9e64-96904ba4a8d2.png">
<img width="1440" alt="orbital5" src="https://user-images.githubusercontent.com/45273497/48924750-81c67f80-ee89-11e8-8cf2-16662b485a80.png">

**Comment by ghost** [comment]
After a bit of inspection, the cubemap itself doesnt seem to operate correctly at all, instead being used as a static overlay instead of a cubemap. This causes the first and last artifacts that were mentioned

**Comment by Satomilee** [comment]
edittag levels\dlc\spacecamp\fx\brainiac_mist\brainiac_mist.prt3
setfield RenderMethod.ShaderProperties[0].Template shaders\particle_templates\_4_10_0_0_1_1_1_0_0_0.rmt2
savetagchanges
exitto tags

edittag levels\dlc\spacecamp\fx\pit_steam\pit_steam.prt3
setfield RenderMethod.ShaderProperties[0].Template shaders\particle_templates\_4_10_0_0_1_1_1_0_0_0.rmt2
savetagchanges
exitto tags
