### ISSUE TITLE
ImportMapVariant

### ISSUE THREAD

**Issue by Newbster-2** [TheGuardians/TagTool#65]
Experiencing many complications with this command, and I'm not sure whether it's how Eldewrito 0.6.1/0.6.0 generates map variants (sandbox.map files) or how TagTool interprets and deserializes them.

Testing Scenario: Using the latest development branch of TagTool and a fresh, clean build of ED 0.6.1, then creating a basic map variant for guardian which does NOT contain the map editor prop.

Debugging in Visual Studio reveals many large, extraneous values in various fields when reading the sandbox.map file:
MapId values above one million
placementIndex values that are negative or way above 640
blf header value above one billion and in turns gives a signature of "????" throwing the error: "System.NotImplementedException: 'BLF chunk type ???? not implemented!'"

Obviously because of these unusable values both the default command and "Mapfile" flag fail to execute properly and throw many errors.

**Comment by Newbster-2** [comment]
Does anybody read these lol.

**Comment by ghost** [comment]
Probably not.
