### ISSUE TITLE
H4 builds are supported?

### ISSUE THREAD

**Issue by MataPuelc0s** [TheGuardians/TagTool#84]
wanted to open maps for research and extraction gives a crash/close app with the next log:

Enter the path to a Halo cache file (.map/.dat):
> ..\Halo 4 (Dec 21, 2011) [09550.11.12.21.0300-0] [Cache Build] [Debug Enabled]\09550.11.12.21.0300-0\maps\m90_sacrifice.map

ERROR: Referencia a objeto no establecida como instancia de un objeto.

STACKTRACE: 
   en TagTool.BlamFile.MapFile.Read(EndianReader reader)
   en TagTool.Cache.GameCache.Open(FileInfo file)
   en TagTool.Commands.Program.Main(String[] args)

**Comment by Modulus32** [comment]
If the build doesn't open, its not supported. Development builds are not always the same as release builds, so if a release build for a game is supported it doesn't mean all of the development builds are.
